name: Zombi_Learning_System
on:
  schedule:
    - cron: '*/45 * * * *'
  workflow_dispatch:

jobs:
  run-and-learn:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: pip install requests

      - name: Zombiyi Calistir
        env:
          TIKTOK_SESSION: ${{ secrets.TIKTOK_SESSION }}
        run: python bot.py

      - name: Hafizayi Guncelle (Learning)
        run: |
          git config --global user.name "Zombi-Bot"
          git config --global user.email "bot@wormgem.ai"
          git add brain.json
          git commit -m "Zombi yeni videolar ögrendi 🇲🇽" || exit 0
          git push
